In [44]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [45]:
medical_dirty = pd.read_csv("realworld_medical_dirty.csv")

In [46]:
medical_clean = medical_dirty.copy()

In [47]:
medical_clean.head(5)

,Patient_ID,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes
0,P1000,55.0,FEMALE,120.0,NaN,35.4,Yes,Heart Disease,2023-12-27,NaN
1,P1001,65.0,Male,150.0,180.0,27.8,NaN,NaN,2023-01-01,NaN
2,P1002,45.0,Male,120.0,220.0,22.5,No,NaN,2023-12-14,NaN
3,P1003,65.0,Male,NaN,180.0,35.4,No,NaN,2023-07-09,NaN
4,P1004,65.0,Male,120.0,300.0,40.1,NaN,NaN,2023-07-10,Follow-up required

**Data Cleaning**

In [48]:
#1. Remove Patient_ID as a column, PII

In [49]:
medical_clean = medical_clean.drop(columns="Patient_ID")

In [50]:
#2 Change Data Type for Admission Data to date time

In [51]:
medical_clean["Admission_Date"] = pd.to_datetime(medical_clean["Admission_Date"])

In [52]:
medical_clean["Month Year"]  = (
    medical_clean["Admission_Date"].dt.month_name() + " " + medical_clean["Admission_Date"].dt.year.astype(str)
)

In [53]:
medical_clean

,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes,Month Year
0,55.0,FEMALE,120.0,NaN,35.4,Yes,Heart Disease,2023-12-27,NaN,December 2023
1,65.0,Male,150.0,180.0,27.8,NaN,NaN,2023-01-01,NaN,January 2023
2,45.0,Male,120.0,220.0,22.5,No,NaN,2023-12-14,NaN,December 2023
3,65.0,Male,NaN,180.0,35.4,No,NaN,2023-07-09,NaN,July 2023
4,65.0,Male,120.0,300.0,40.1,NaN,NaN,2023-07-10,Follow-up required,July 2023
...,...,...,...,...,...,...,...,...,...,...
95,55.0,MALE,150.0,200.0,35.4,Yes,NaN,2023-07-16,Follow-up required,July 2023
96,55.0,male,NaN,220.0,27.8,Y,NaN,2023-12-17,Follow-up required,December 2023
97,65.0,Female,150.0,200.0,27.8,N,NaN,2023-05-13,Checkup due,May 2023
98,25.0,MALE,NaN,180.0,40.1,Yes,Diabetes,2023-12-24,Follow-up required,December 2023
99,65.0,NaN,140.0,300.0,35.4,N,NaN,2023-09-16,NaN,September 2023

In [54]:
medical_clean["Year"] = medical_clean["Year"] = medical_clean["Admission_Date"].dt.year.astype(str)

In [55]:
medical_clean

,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes,Month Year,Year
0,55.0,FEMALE,120.0,NaN,35.4,Yes,Heart Disease,2023-12-27,NaN,December 2023,2023
1,65.0,Male,150.0,180.0,27.8,NaN,NaN,2023-01-01,NaN,January 2023,2023
2,45.0,Male,120.0,220.0,22.5,No,NaN,2023-12-14,NaN,December 2023,2023
3,65.0,Male,NaN,180.0,35.4,No,NaN,2023-07-09,NaN,July 2023,2023
4,65.0,Male,120.0,300.0,40.1,NaN,NaN,2023-07-10,Follow-up required,July 2023,2023
...,...,...,...,...,...,...,...,...,...,...,...
95,55.0,MALE,150.0,200.0,35.4,Yes,NaN,2023-07-16,Follow-up required,July 2023,2023
96,55.0,male,NaN,220.0,27.8,Y,NaN,2023-12-17,Follow-up required,December 2023,2023
97,65.0,Female,150.0,200.0,27.8,N,NaN,2023-05-13,Checkup due,May 2023,2023
98,25.0,MALE,NaN,180.0,40.1,Yes,Diabetes,2023-12-24,Follow-up required,December 2023,2023
99,65.0,NaN,140.0,300.0,35.4,N,NaN,2023-09-16,NaN,September 2023,2023

In [56]:
#3 fill in null values for Notes and Diagnosis and smoker

In [57]:
medical_clean["Notes"] = medical_clean["Notes"].fillna("No Follow Up Notes Were Captured")

In [58]:
medical_clean["Diagnosis"] = medical_clean["Diagnosis"].fillna("No Diagnosis Was Administered")

In [59]:
medical_clean["Smoker"] = medical_clean["Smoker"].fillna("Not Sure If They Are a Smoker")

In [60]:
medical_clean["Smoker"] = medical_clean["Smoker"].replace({
    "Y": "Yes",
    "N": "No"
})

In [61]:
#4 Clean up Gender Column

In [62]:
medical_clean["Gender"] = medical_clean["Gender"].fillna("Unknown Gender")

In [63]:
medical_clean["Gender"].value_counts()

Gender
Male              22
MALE              21
Female            17
FEMALE            15
Unknown Gender    15
male              10
Name: count, dtype: int64

In [64]:
medical_clean["Gender"] = medical_clean["Gender"].replace({
    "MALE": "Male",
    "male": "Male",
    "FEMALE": "Female"
})

In [65]:
medical_clean["Gender"] = medical_clean["Gender"].str.strip().str.title()

In [66]:
medical_clean["Gender"].value_counts()

Gender
Male              53
Female            32
Unknown Gender    15
Name: count, dtype: int64

In [67]:
#4 check if there are nulls in the age, blood pressure, cholestrol and BMI categories, if so handle them apporiately

In [68]:
cols = ["Age", "Blood_Pressure", "Cholesterol", "BMI"]

In [69]:
null_counts = medical_clean[cols].isnull().sum()
null_pct = (null_counts / len(medical_clean) * 100).round(2)

null_summary = pd.DataFrame({
    'null_count': null_counts,
    'null_pct': null_pct
})

In [70]:
print(null_summary[null_summary['null_count'] > 0])

                null_count  null_pct
Age                     17      17.0
Blood_Pressure          14      14.0
Cholesterol             20      20.0
BMI                     20      20.0

In [71]:
medical_clean.head(5)

,Age,Gender,Blood_Pressure,Cholesterol,BMI,Smoker,Diagnosis,Admission_Date,Notes,Month Year,Year
0,55.0,Female,120.0,NaN,35.4,Yes,Heart Disease,2023-12-27,No Follow Up Notes Were Captured,December 2023,2023
1,65.0,Male,150.0,180.0,27.8,Not Sure If They Are a Smoker,No Diagnosis Was Administered,2023-01-01,No Follow Up Notes Were Captured,January 2023,2023
2,45.0,Male,120.0,220.0,22.5,No,No Diagnosis Was Administered,2023-12-14,No Follow Up Notes Were Captured,December 2023,2023
3,65.0,Male,NaN,180.0,35.4,No,No Diagnosis Was Administered,2023-07-09,No Follow Up Notes Were Captured,July 2023,2023
4,65.0,Male,120.0,300.0,40.1,Not Sure If They Are a Smoker,No Diagnosis Was Administered,2023-07-10,Follow-up required,July 2023,2023

In [72]:
from scipy import stats

num_cols = ["Age", "Blood_Pressure", "Cholesterol", "BMI"]
cat_cols = ["Gender", "Smoker", "Diagnosis", "Notes", "Year"]

In [73]:
rows = []
for target in num_cols:
    is_missing = medical_clean[target].isnull()

    # Categorical columns: chi-square test
    for col in cat_cols:
        table = pd.crosstab(medical_clean[col], is_missing)
        chi2, p, dof, expected = stats.chi2_contingency(table)
        rows.append({"missing_col": target, "vs": col, "test": "chi-square",
                     "p_value": round(p, 4), "min_expected": round(expected.min(), 1)})

    # Numeric columns: compare values when target is missing vs present
    for col in num_cols:
        if col == target:
            continue
        missing_grp = medical_clean.loc[is_missing, col].dropna()
        present_grp = medical_clean.loc[~is_missing, col].dropna()
        stat, p = stats.mannwhitneyu(missing_grp, present_grp)
        rows.append({"missing_col": target, "vs": col, "test": "Mann-Whitney",
                     "p_value": round(p, 4), "min_expected": None})

results = pd.DataFrame(rows).sort_values("p_value")
results

       missing_col              vs          test  p_value  min_expected
14  Blood_Pressure     Cholesterol  Mann-Whitney   0.0521           NaN
1              Age          Smoker    chi-square   0.0567           3.4
17     Cholesterol          Smoker    chi-square   0.1213           4.0
22     Cholesterol  Blood_Pressure  Mann-Whitney   0.1347           NaN
29             BMI             Age  Mann-Whitney   0.1355           NaN
31             BMI     Cholesterol  Mann-Whitney   0.1434           NaN
7              Age             BMI  Mann-Whitney   0.1458           NaN
2              Age       Diagnosis    chi-square   0.1602           4.2
8   Blood_Pressure          Gender    chi-square   0.1699           2.1
21     Cholesterol             Age  Mann-Whitney   0.1749           NaN
15  Blood_Pressure             BMI  Mann-Whitney   0.2673           NaN
5              Age  Blood_Pressure  Mann-Whitney   0.2782           NaN
10  Blood_Pressure       Diagnosis    chi-square   0.3083           3.5
6              Age     Cholesterol  Mann-Whitney   0.3544           NaN
25             BMI          Smoker    chi-square   0.3916           4.0
11  Blood_Pressure           Notes    chi-square   0.3996           2.0
30             BMI  Blood_Pressure  Mann-Whitney   0.4608           NaN
16     Cholesterol          Gender    chi-square   0.4774           3.0
27             BMI           Notes    chi-square   0.5587           2.8
13  Blood_Pressure             Age  Mann-Whitney   0.5668           NaN
19     Cholesterol           Notes    chi-square   0.6203           2.8
3              Age           Notes    chi-square   0.6929           2.4
26             BMI       Diagnosis    chi-square   0.7625           5.0
9   Blood_Pressure          Smoker    chi-square   0.8470           2.8
0              Age          Gender    chi-square   0.8992           2.6
23     Cholesterol             BMI  Mann-Whitney   0.9164           NaN
18     Cholesterol       Diagnosis    chi-square   0.9370           5.0
24             BMI          Gender    chi-square   0.9452           3.0
12  Blood_Pressure            Year    chi-square   1.0000          14.0
4              Age            Year    chi-square   1.0000          17.0
20     Cholesterol            Year    chi-square   1.0000          20.0
28             BMI            Year    chi-square   1.0000          20.0

In [74]:
medical_clean[num_cols].isnull().corr()

                     Age  Blood_Pressure   Cholesterol           BMI
Age             1.000000       -0.105877 -9.317610e-02 -9.317610e-02
Blood_Pressure -0.105877        1.000000 -5.763904e-02  1.585074e-01
Cholesterol    -0.093176       -0.057639  1.000000e+00  1.821460e-17
BMI            -0.093176        0.158507  1.821460e-17  1.000000e+00

In [75]:
pd.crosstab(medical_clean["Smoker"], medical_clean["Age"].isnull(), normalize="index")

Age                            False  True
Smoker
No                             0.875  0.125
Not Sure If They Are a Smoker  0.950  0.050
Yes                            0.725  0.275

In [76]:
#5 apply median imputation to replace the null values for the numeric values

In [77]:
for col in num_cols:
    medical_clean[f"{col}_was_missing"] = medical_clean[col].isnull()
    medical_clean[col] = medical_clean[col].fillna(medical_clean[col].median())

In [78]:
null_counts = medical_clean[cols].isnull().sum()
null_pct = (null_counts / len(medical_clean) * 100).round(2)

null_summary = pd.DataFrame({
    'null_count': null_counts,
    'null_pct': null_pct
})

In [79]:
print(null_summary[null_summary['null_count'] > 0])

Empty DataFrame
Columns: [null_count, null_pct]
Index: []

In [80]:
medical_clean.dtypes

Age                                  float64
Gender                                   str
Blood_Pressure                       float64
Cholesterol                          float64
BMI                                  float64
Smoker                                   str
Diagnosis                                str
Admission_Date                datetime64[us]
Notes                                    str
Month Year                               str
Year                                     str
Age_was_missing                         bool
Blood_Pressure_was_missing              bool
Cholesterol_was_missing                 bool
BMI_was_missing                         bool
dtype: object